export enum EToastMessage  {
    QR_CODE_INVALID = "Invalid QR Code",
    CONNECTED = "Connected successfully",
    MEMBER_ADDED = "Member added",
    MEMBER_UPDATED = "Member updated",
    FAILED_TO_UPDATE_MEMBER = "Failed to update member. Try again later.",
    FAILED_TO_CREATE_MEMBER = "Failed to add member",
    FAILED_TO_CREATE_QUESTION = "Failed to create questions",
    FAILED_TO_UPDATE_QUESTION = "Failed to update questions",
    QUESTION_DELETED = "Question deleted",
    UNKOWN_ERROR = "Unkown error",
    FAILED_TO_SAVE_QUIZ = "Failed to save quiz",
    QUIZ_DELETED = "1 Quiz deleted",
    QUIZ_ADDED = "1 Quiz added",
    QUIZ_FAIL_TO_ADD = "failed to add quiz",
}