import { EMemberRole } from "@/enums";
import { IMember } from "@/interfaces";

export const mockMembers: IMember[] = [
  {
    _id: "1",
    email: "john.doe@example.com",
    firstName: "John",
    facebookName: "John Doe",
    role: EMemberRole.ADMIN,
    password: "hashed_password",
    totalScore: 1250,
  },
  {
    _id: "2",
    email: "jane.smith@example.com",
    firstName: "Jane",
    facebookName: "Jane Smith",
    role: EMemberRole.MODERATOR,
    password: "hashed_password",
    totalScore: 980,
  },
  {
    _id: "3",
    email: "michael.johnson@example.com",
    firstName: "Michael",
    facebookName: "Michael Johnson",
    role: EMemberRole.MEMBER,
    password: "hashed_password",
    totalScore: 750,
  },
  {
    _id: "4",
    email: "emily.wilson@example.com",
    firstName: "Emily",
    facebookName: "Emily Wilson",
    role: EMemberRole.MEMBER,
    password: "hashed_password",
    totalScore: 820,
  },
  {
    _id: "5",
    email: "david.brown@example.com",
    firstName: "David",
    facebookName: "David Brown",
    role: EMemberRole.MEMBER,
    password: "hashed_password",
    totalScore: 690,
  },
  {
    _id: "6",
    email: "sarah.taylor@example.com",
    firstName: "Sarah",
    facebookName: "Sarah Taylor",
    role: EMemberRole.MODERATOR,
    password: "hashed_password",
    totalScore: 1100,
  },
  {
    _id: "7",
    email: "james.anderson@example.com",
    firstName: "James",
    facebookName: "James Anderson",
    role: EMemberRole.MEMBER,
    password: "hashed_password",
    totalScore: 580,
  },
  {
    _id: "8",
    email: "olivia.thomas@example.com",
    firstName: "Olivia",
    facebookName: "Olivia Thomas",
    role: EMemberRole.MEMBER,
    password: "hashed_password",
    totalScore: 720,
  },
  {
    _id: "9",
    email: "william.jackson@example.com",
    firstName: "William",
    facebookName: "William Jackson",
    role: EMemberRole.MEMBER,
    password: "hashed_password",
    totalScore: 850,
  },
  {
    _id: "10",
    email: "sophia.white@example.com",
    firstName: "Sophia",
    facebookName: "Sophia White",
    role: EMemberRole.MEMBER,
    password: "hashed_password",
    totalScore: 930,
  },
]